ALTER TABLE devices
    DROP COLUMN IF EXISTS vendor,
    DROP COLUMN IF EXISTS management_controller,
    DROP COLUMN IF EXISTS protocol,
    DROP COLUMN IF EXISTS polling_interval,
    DROP COLUMN IF EXISTS ssl_verify;

ALTER TABLE device_inventory
    DROP COLUMN IF EXISTS service_tag,
    DROP COLUMN IF EXISTS asset_tag,
    DROP COLUMN IF EXISTS system_model,
    DROP COLUMN IF EXISTS manufacturer,
    DROP COLUMN IF EXISTS power_state,
    DROP COLUMN IF EXISTS health_status,
    DROP COLUMN IF EXISTS bmc_firmware,
    DROP COLUMN IF EXISTS bmc_mac_address,
    DROP COLUMN IF EXISTS bmc_dns_name,
    DROP COLUMN IF EXISTS bmc_license,
    DROP COLUMN IF EXISTS bmc_hardware_version,
    DROP COLUMN IF EXISTS lifecycle_controller_ver,
    DROP COLUMN IF EXISTS total_power_watts,
    DROP COLUMN IF EXISTS memory_total_gb,
    DROP COLUMN IF EXISTS processors_json,
    DROP COLUMN IF EXISTS memory_modules_json,
    DROP COLUMN IF EXISTS storage_controllers_json,
    DROP COLUMN IF EXISTS drives_json,
    DROP COLUMN IF EXISTS temperatures_json,
    DROP COLUMN IF EXISTS fans_json,
    DROP COLUMN IF EXISTS power_supplies_json,
    DROP COLUMN IF EXISTS nics_json,
    DROP COLUMN IF EXISTS sel_entries_json,
    DROP COLUMN IF EXISTS accelerators_json,
    DROP COLUMN IF EXISTS pcie_slots_json,
    DROP COLUMN IF EXISTS voltages_json;
